baseURL = "https://cp-remodeling.github.io/"
languageCode = "en-AU"
theme = "hugo-icon"
title = "Clifton Park Remodeling"
[params]
author = "Terry Nellis"
description = "Clifton Park Remodeling provides quality work at reasonable prices.  We have over 20 years of business experience operating in the Albany, Schenectady, Troy, & Saratoga - Capital Region of New York"
[params.contact]
enable = true
message = "Please <a href='mailto:cliftonparkremodeling@gmail.com'>send an email</a> OR use the contact form below.  We will set up an appoinment as soon as possible."
title = "Need a Quote?"
[params.footer]
enable = true
facebook = "#"
linkedin = "#"
note = "<p><small>&copy; 2017 Clifton Park Remodeling - Website by  <a href=\"chrislabargedev@gmail.com\">Chris LaBarge</a></p>"
[params.hero]
description = "Providing Home and Commercial Remodeling in the Capital Region of New York since 1995"
img = "images/hero_bg.jpg"
title = "Clifton Park Remodeling"
[params.mission]
enable = true
[params.mission.images]
enable = false
[[params.mission.images.list]]
img = "images/img_3.jpg"
[[params.mission.images.list]]
img = "images/img_2.jpg"
[[params.mission.images.list]]
img = "images/img_1.jpg"
[[params.mission.images.list]]
img = "images/img_4.jpg"
[[params.mission.item]]
description = "<p>We are a Home & Commercial Improvement company that offers a wide variety of services. We handle everything from carpentry, demolition, development and much more! We have years of experience, and hundreds of happy and satisfied customers. We also will provide before and after photos available per your request. We offer free estimates and will work on any size project, big or small.</p><ul class='checked'><li>Multitude of Services</li><li>Free Estimates</li><li>Quality Work</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"
name = "about"
subtitle = "Clifton Park Remodeling"
title = "Who We Are"
weight = 1
[[params.mission.item]]
description = "<ul class='checked'><li>Carpentry</li><li>Tile/Masonry</li><li>Kitchens</li><li>Bathrooms</li><li>Basements</li><li>Lighting</li><li>Outdoor Deck/Patio</li><li>Siding</li><li>Windows</li><li>Doors</li><li>Drywall</li><li>Painting</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"
name = "services"
subtitle = "Are services include, but are not limited to:"
title = "Services"
weight = 2
[params.nav]
contact = "Get In Touch"
mission = "About"
service = "Services"
services = "Why Us?"
[params.services]
description = "You can drive yourself mad looking for the right company for your project. Here is why you should come to us first!"
enable = true
title = "Why go with Clifton Park Remodeling?"
video = false
vidlink = ""
[[params.services.item]]
description = "From communication, to craftsmanship, we make sure to provide you with only the best quality experience all around."
icon = "icon-wrench"
title = "Top Quality Work"
[[params.services.item]]
description = "We pride ourselves on making sure our finished product is reliable and durable, preventing unnessary fixes & maintenance."
icon = "icon-like"
title = "Done Right the first time"
[[params.services.item]]
description = "We have been in the business a long time, and can provide you with first hand knowledge of what will and will not work."
icon = "icon-badge"
title = "Years of experience"
[params.team]
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
enable = false
title = "Meet The Team"
[[params.team.item]]
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
dribbble = "#"
facebook = "#"
github = "#"
img = "images/person1.jpg"
instagram = "#"
linkedin = "#"
name = "Jean Doe"
position = "Chief legend"
twitter = "#"
[[params.team.item]]
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
dribbble = "#"
facebook = "#"
github = "#"
img = "images/person2.jpg"
instagram = "#"
name = "Alice Doe"
position = "Chief overlord"
twitter = "#"
[[params.team.item]]
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
dribbble = "#"
facebook = "#"
github = "#"
img = "images/person3.jpg"
instagram = "#"
name = "John Doe"
position = "Chief haranguer"
twitter = "#"
[params.work]
enable = true
[[params.work.item]]
img = "images/stairs.jpg"
subtitle = "Stairscase Entryway"
title = "Home Remodel"
[[params.work.item]]
img = "images/floor.jpg"
subtitle = "Tile Floor"
title = "Commercial Remodel"
[[params.work.item]]
img = "images/basement.jpg"
subtitle = "Basement Den"
title = "Home Remodel"
[[params.work.item]]
img = "images/kitchen.jpg"
subtitle = "Kitchen"
title = "Home Remodel"
